### ISSUE TITLE
Crash (segfault) on Raspberry Pi 4

### ISSUE THREAD

**Issue by vanfanel** [coelckers/Raze#281]
Hi again,

I have just tried building RAZE on the Pi4 (aarch64).
Building process went well, but I got this when trying to run RAZE with duke3d.grp and raze.pk3 on the same directory as the raze executable:
```

Using video driver KMSDRM
[....................................................................................................................................]
Thread 1 "raze" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000007ff7f3282c in SDL_EGL_ChooseConfig () from /usr/local/lib/libSDL2-2.0.so.0
#2  0x0000007ff7f330e8 in SDL_EGL_CreateSurface () from /usr/local/lib/libSDL2-2.0.so.0
#3  0x0000007ff7f4d4e8 in KMSDRM_CreateSurfaces () from /usr/local/lib/libSDL2-2.0.so.0
#4  0x0000007ff7f4d994 in KMSDRM_ReconfigureWindow () from /usr/local/lib/libSDL2-2.0.so.0
#5  0x0000007ff7f3c4ac in SDL_UpdateFullscreenMode () from /usr/local/lib/libSDL2-2.0.so.0
#6  0x0000007ff7f3cae0 in SDL_SetWindowFullscreen_REAL () from /usr/local/lib/libSDL2-2.0.so.0
#7  0x0000007ff7f3d760 in SDL_FinishWindowCreation () from /usr/local/lib/libSDL2-2.0.so.0
#8  0x0000007ff7f3f878 in SDL_CreateWindow_REAL () from /usr/local/lib/libSDL2-2.0.so.0
#9  0x00000055557fecdc in Priv::CreateWindow (extraFlags=4099)
    at /home/pi/src/Raze/source/common/platform/posix/sdl/sdlglvideo.cpp:169
#10 0x00000055557ff66c in SystemGLFrameBuffer::SystemGLFrameBuffer (this=0x555bc026d0, hMonitor=0x0, fullscreen=true)
    at /home/pi/src/Raze/source/common/platform/posix/sdl/sdlglvideo.cpp:657
#11 0x0000005555ac86a8 in OpenGLRenderer::OpenGLFrameBuffer::OpenGLFrameBuffer (this=0x555bc026d0, hMonitor=0x0, fullscreen=true)
    at /home/pi/src/Raze/source/common/rendering/gl/gl_framebuffer.cpp:86
#12 0x00000055557ff054 in SDLVideo::CreateFrameBuffer (this=0x55597eba20)
    at /home/pi/src/Raze/source/common/platform/posix/sdl/sdlglvideo.cpp:500
#13 0x0000005555a9d2d8 in IVideo::SetResolution (this=0x55597eba20) at /home/pi/src/Raze/source/common/rendering/v_video.cpp:303
#14 0x0000005555a9d610 in V_Init2 () at /home/pi/src/Raze/source/common/rendering/v_video.cpp:379
#15 0x000000555590725c in videoInit () at /home/pi/src/Raze/source/core/gamecontrol.cpp:1011
#16 0x0000005555906e74 in RunGame () at /home/pi/src/Raze/source/core/gamecontrol.cpp:929
#17 0x00000055559059a0 in GameMain () at /home/pi/src/Raze/source/core/gamecontrol.cpp:539
#18 0x00000055557fd9f0 in main (argc=1, argv=0x7ffffff658) at /home/pi/src/Raze/source/common/platform/posix/sdl/i_main.cpp:194
```

Maybe desktop GL is needed? Does RAZE support Vulkan rendering or GLES2/3?

**Comment by coelckers** [comment]
> Maybe desktop GL is needed? Does RAZE support Vulkan rendering or GLES2/3?

Yes, it is. The vulkan backend unfortunately does not work yet so it is normally disabled.

**Comment by vanfanel** [comment]
@coelckers Ok! Well, Pi4 compatibility would be expected to be optimal through Vulkan I guess.

Thanks!
